import * as Notifications from 'expo-notifications';
import * as SecureStore from 'expo-secure-store';
import { Platform } from 'react-native';
Notifications.setNotificationHandler({handleNotification:async()=>({shouldShowAlert:true,shouldPlaySound:false,shouldSetBadge:false})});
const CHECKIN_NOTIFICATION_ID_KEY='still_checkin_notification_id';const WATER_NOTIFICATION_ID_KEY='still_decoy_water_notification_id';
export async function requestNotificationPermissions(){if(Platform.OS==='web')return false;const{status:existingStatus}=await Notifications.getPermissionsAsync();let finalStatus=existingStatus;if(existingStatus!=='granted'){const{status}=await Notifications.requestPermissionsAsync();finalStatus=status;}return finalStatus==='granted';}
async function cancelStoredNotification(storageKey:string){if(Platform.OS==='web')return;const prevId=await SecureStore.getItemAsync(storageKey);if(prevId)await Notifications.cancelScheduledNotificationAsync(prevId).catch(()=>{});}async function storeScheduledNotificationId(storageKey:string,id:string){try{await SecureStore.setItemAsync(storageKey,id);}catch(error){await Notifications.cancelScheduledNotificationAsync(id).catch(()=>{});throw error;}}
async function isStoredNotificationScheduled(storageKey:string){if(Platform.OS==='web')return false;const storedId=await SecureStore.getItemAsync(storageKey);if(!storedId)return false;try{const{status}=await Notifications.getPermissionsAsync();if(status!=='granted')return false;const scheduled=await Notifications.getAllScheduledNotificationsAsync();const stillScheduled=scheduled.some(n=>n.identifier===storedId);if(!stillScheduled)await SecureStore.deleteItemAsync(storageKey);return stillScheduled;}catch{return false;}}
export async function scheduleDailyCheckinNotification(hour=20,minute=0){const granted=await requestNotificationPermissions();if(!granted)return null;await cancelStoredNotification(CHECKIN_NOTIFICATION_ID_KEY);const id=await Notifications.scheduleNotificationAsync({content:{title:'Still',body:'A quiet moment, whenever you’re ready.',sound:true},trigger:{type:Notifications.SchedulableTriggerInputTypes.DAILY,hour,minute}});await storeScheduledNotificationId(CHECKIN_NOTIFICATION_ID_KEY,id);return id;}
export async function cancelCheckinReminder(){await cancelStoredNotification(CHECKIN_NOTIFICATION_ID_KEY);await SecureStore.deleteItemAsync(CHECKIN_NOTIFICATION_ID_KEY);}export async function isCheckinReminderScheduled(){return isStoredNotificationScheduled(CHECKIN_NOTIFICATION_ID_KEY);}export async function isWaterReminderScheduled(){return isStoredNotificationScheduled(WATER_NOTIFICATION_ID_KEY);}
export async function scheduleWaterReminder(hour:number,minute:number){const granted=await requestNotificationPermissions();if(!granted)return null;await cancelStoredNotification(WATER_NOTIFICATION_ID_KEY);const id=await Notifications.scheduleNotificationAsync({content:{title:'💧 Hydration Reminder',body:'Time for a glass of water — tap to log it.',sound:true},trigger:{type:Notifications.SchedulableTriggerInputTypes.DAILY,hour,minute}});await storeScheduledNotificationId(WATER_NOTIFICATION_ID_KEY,id);return id;}
export async function cancelWaterReminder(){await cancelStoredNotification(WATER_NOTIFICATION_ID_KEY);await SecureStore.deleteItemAsync(WATER_NOTIFICATION_ID_KEY);}export async function cancelAllReminders(){await Notifications.cancelAllScheduledNotificationsAsync();}
