import * as LocalAuthentication from 'expo-local-authentication';
import * as SecureStore from 'expo-secure-store';
import * as Crypto from 'expo-crypto';
import { Platform } from 'react-native';
const BIOMETRIC_ENABLED_KEY='still_biometric_enabled';const PIN_PASSCODE_KEY='still_pin_passcode';const PIN_SALT_KEY='still_pin_salt';const DECOY_PIN_KEY='still_decoy_pin';const PRIVACY_GUARD_KEY='still_privacy_guard';const FAILED_ATTEMPTS_KEY='still_pin_failed_attempts';const LOCKOUT_UNTIL_KEY='still_pin_lockout_until';const LOCKOUT_THRESHOLD=5;const LOCKOUT_STEPS_MS=[30000,60000,300000,900000];
async function hashPin(pin:string,salt:string){return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,`${salt}:${pin}`);}async function storedPinMatches(pin:string){const storedHash=await SecureStore.getItemAsync(PIN_PASSCODE_KEY);const storedSalt=await SecureStore.getItemAsync(PIN_SALT_KEY);return Boolean(storedHash&&storedSalt&&(await hashPin(pin,storedSalt))===storedHash);}async function storedDecoyMatches(pin:string){const decoyStored=await SecureStore.getItemAsync(DECOY_PIN_KEY);const[decoySalt,decoyHash]=decoyStored?.split(':')??[];return Boolean(decoySalt&&decoyHash&&(await hashPin(pin,decoySalt))===decoyHash);}function randomSalt(){const bytes=Crypto.getRandomBytes(16);return Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('');}
export interface SecuritySettings{biometricsEnabled:boolean;hasPinSet:boolean;privacyGuardEnabled:boolean;}
export async function getSecuritySettings():Promise<SecuritySettings>{let biometricsEnabled=false,hasPinSet=false,privacyGuardEnabled=true;if(Platform.OS==='web')return{biometricsEnabled,hasPinSet,privacyGuardEnabled};try{biometricsEnabled=(await SecureStore.getItemAsync(BIOMETRIC_ENABLED_KEY))==='true';const pinVal=await SecureStore.getItemAsync(PIN_PASSCODE_KEY);hasPinSet=Boolean(pinVal&&pinVal.length>=4);const privVal=await SecureStore.getItemAsync(PRIVACY_GUARD_KEY);if(privVal!==null)privacyGuardEnabled=privVal==='true';}catch(e){console.warn('SecureStore error reading security settings:',e);}return{biometricsEnabled,hasPinSet,privacyGuardEnabled};}
export async function setBiometricsEnabled(enabled:boolean){if(Platform.OS==='web')return false;try{if(enabled){const hasHardware=await LocalAuthentication.hasHardwareAsync();const isEnrolled=await LocalAuthentication.isEnrolledAsync();if(!hasHardware||!isEnrolled)return false;}await SecureStore.setItemAsync(BIOMETRIC_ENABLED_KEY,enabled?'true':'false');return true;}catch{return false;}}
export async function setPinPasscode(pin:string){if(Platform.OS==='web')return;if(await storedDecoyMatches(pin))throw new Error('pin_matches_decoy_pin');const salt=randomSalt();const hash=await hashPin(pin,salt);await SecureStore.setItemAsync(PIN_SALT_KEY,salt);await SecureStore.setItemAsync(PIN_PASSCODE_KEY,hash);}
export async function setDecoyPasscode(pin:string|null){if(Platform.OS==='web')return;if(pin===null){await SecureStore.deleteItemAsync(DECOY_PIN_KEY);return;}if(await storedPinMatches(pin))throw new Error('decoy_pin_matches_real_pin');const salt=randomSalt();const hash=await hashPin(pin,salt);await SecureStore.setItemAsync(DECOY_PIN_KEY,`${salt}:${hash}`);}
export async function hasDecoyPasscode(){if(Platform.OS==='web')return false;return Boolean(await SecureStore.getItemAsync(DECOY_PIN_KEY));}
export interface PinVerifyResult{valid:boolean;isDecoy:boolean;lockedOutMs?:number;}
export async function verifyPinPasscode(pin:string):Promise<PinVerifyResult>{if(Platform.OS==='web')return{valid:true,isDecoy:false};if(await storedDecoyMatches(pin)){await clearFailedAttempts();return{valid:true,isDecoy:true};}const lockoutUntilRaw=await SecureStore.getItemAsync(LOCKOUT_UNTIL_KEY);const lockoutUntil=lockoutUntilRaw?parseInt(lockoutUntilRaw,10):0;const now=Date.now();if(lockoutUntil>now)return{valid:false,isDecoy:false,lockedOutMs:lockoutUntil-now};const storedHash=await SecureStore.getItemAsync(PIN_PASSCODE_KEY);const storedSalt=await SecureStore.getItemAsync(PIN_SALT_KEY);if(!storedHash||!storedSalt)return{valid:false,isDecoy:false};if(await storedPinMatches(pin)){await clearFailedAttempts();return{valid:true,isDecoy:false};}const attempts=await recordFailedAttempt();if(attempts>=LOCKOUT_THRESHOLD){const stepIdx=Math.min(attempts-LOCKOUT_THRESHOLD,LOCKOUT_STEPS_MS.length-1);const lockoutMs=LOCKOUT_STEPS_MS[stepIdx]??LOCKOUT_STEPS_MS[LOCKOUT_STEPS_MS.length-1]!;await SecureStore.setItemAsync(LOCKOUT_UNTIL_KEY,String(now+lockoutMs));return{valid:false,isDecoy:false,lockedOutMs:lockoutMs};}return{valid:false,isDecoy:false};}
async function recordFailedAttempt(){const raw=await SecureStore.getItemAsync(FAILED_ATTEMPTS_KEY);const count=(raw?parseInt(raw,10):0)+1;await SecureStore.setItemAsync(FAILED_ATTEMPTS_KEY,String(count));return count;}async function clearFailedAttempts(){await SecureStore.deleteItemAsync(FAILED_ATTEMPTS_KEY);await SecureStore.deleteItemAsync(LOCKOUT_UNTIL_KEY);}
export async function authenticateWithBiometrics(){if(Platform.OS==='web')return false;try{if((await SecureStore.getItemAsync(BIOMETRIC_ENABLED_KEY))!=='true')return false;const hasHardware=await LocalAuthentication.hasHardwareAsync();const isEnrolled=await LocalAuthentication.isEnrolledAsync();if(!hasHardware||!isEnrolled)return false;const res=await LocalAuthentication.authenticateAsync({promptMessage:'Unlock Still private data',fallbackLabel:'Use Passcode',cancelLabel:'Cancel',disableDeviceFallback:false});return res.success;}catch{return false;}}
