import { Platform } from 'react-native';
import type * as SQLite from 'expo-sqlite';
import { calculateCurrentStreakDays, calculatePledgeStreak } from '../utils/streak-metrics';
export interface UrgeRecord{id?:number;timestamp:number;intensity:number;trigger_type:string;resolution:'resisted'|'relapsed'|'interrupted';notes?:string;duration_seconds:number;}
export interface JournalEntry{id?:number;timestamp:number;type:'text'|'audio'|'video';title:string;content_or_uri:string;mood?:string;tags?:string;}
export interface StreakInfo{currentStreakDays:number;totalResisted:number;lastUrgeTimestamp:number|null;} export interface PledgeRecord{id?:number;timestamp:number;}
export interface StillDatabase{execAsync(sql:string):Promise<void>;runAsync(sql:string,params?:any[]):Promise<{lastInsertRowId:number}>;getAllAsync<T>(sql:string,params?:any[]):Promise<T[]>;getFirstAsync<T>(sql:string,params?:any[]):Promise<T|null>;}
const webMockDatabase:StillDatabase={execAsync:async()=>{},runAsync:async()=>({lastInsertRowId:1}),getAllAsync:async<T>()=>[] as T[],getFirstAsync:async<T>()=>null as T|null};let dbInstance:StillDatabase|null=null;
export async function getDatabase():Promise<StillDatabase>{if(Platform.OS==='web')return webMockDatabase;if(!dbInstance){const SQLite=require('expo-sqlite');const db:SQLite.SQLiteDatabase=await SQLite.openDatabaseAsync('still_private.db');await initSchema(db);dbInstance=db as unknown as StillDatabase;}return dbInstance;}
async function initSchema(db:SQLite.SQLiteDatabase){await db.execAsync(`PRAGMA journal_mode = WAL; CREATE TABLE IF NOT EXISTS urges (id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp INTEGER NOT NULL,intensity INTEGER NOT NULL,trigger_type TEXT NOT NULL,resolution TEXT NOT NULL,notes TEXT,duration_seconds INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS journal_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp INTEGER NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,content_or_uri TEXT NOT NULL,mood TEXT,tags TEXT); CREATE TABLE IF NOT EXISTS streak_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,start_timestamp INTEGER NOT NULL,end_timestamp INTEGER,notes TEXT); CREATE TABLE IF NOT EXISTS pledges (id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS grounding_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp INTEGER NOT NULL,responses TEXT NOT NULL);`);}
export async function logUrge(urge:Omit<UrgeRecord,'id'>){const db=await getDatabase();const result=await db.runAsync(`INSERT INTO urges (timestamp,intensity,trigger_type,resolution,notes,duration_seconds) VALUES (?,?,?,?,?,?);`,[urge.timestamp,urge.intensity,urge.trigger_type,urge.resolution,urge.notes||'',urge.duration_seconds]);return result.lastInsertRowId;}
export async function getAllUrges(limit=50){const db=await getDatabase();return db.getAllAsync<UrgeRecord>(`SELECT * FROM urges ORDER BY timestamp DESC LIMIT ?;`,[limit]);}
export async function getUrgeStreakStats():Promise<StreakInfo>{const db=await getDatabase();const[lastUrge,totalResistedRow,lastRelapse,firstUrge]=await Promise.all([db.getFirstAsync<Pick<UrgeRecord,'timestamp'>>(`SELECT timestamp FROM urges ORDER BY timestamp DESC LIMIT 1;`),db.getFirstAsync<{count:number}>(`SELECT COUNT(*) as count FROM urges WHERE resolution = 'resisted' OR resolution = 'interrupted';`),db.getFirstAsync<Pick<UrgeRecord,'timestamp'>>(`SELECT timestamp FROM urges WHERE resolution = 'relapsed' ORDER BY timestamp DESC LIMIT 1;`),db.getFirstAsync<Pick<UrgeRecord,'timestamp'>>(`SELECT timestamp FROM urges ORDER BY timestamp ASC LIMIT 1;`)]);return{currentStreakDays:calculateCurrentStreakDays(firstUrge?firstUrge.timestamp:null,lastRelapse?lastRelapse.timestamp:null),totalResisted:totalResistedRow?totalResistedRow.count:0,lastUrgeTimestamp:lastUrge?lastUrge.timestamp:null};}
export async function resetStreak(){const db=await getDatabase();await db.runAsync(`INSERT INTO streak_logs (start_timestamp,notes) VALUES (?,?);`,[Date.now(),'Manual Streak Reset']);await db.runAsync(`INSERT INTO urges (timestamp,intensity,trigger_type,resolution,notes,duration_seconds) VALUES (?,?,?,?,?,?);`,[Date.now(),5,'Manual Reset','relapsed','Streak manually reset by user',0]);}
export async function clearAllData(){const db=await getDatabase();await db.execAsync(`PRAGMA secure_delete = ON;`);try{await db.execAsync(`BEGIN IMMEDIATE; DELETE FROM urges; DELETE FROM journal_entries; DELETE FROM streak_logs; DELETE FROM pledges; DELETE FROM grounding_sessions; DELETE FROM sqlite_sequence WHERE name IN ('urges','journal_entries','streak_logs','pledges','grounding_sessions'); COMMIT;`);}catch(error){await db.execAsync(`ROLLBACK;`).catch(()=>{});throw error;}await db.execAsync(`PRAGMA wal_checkpoint(TRUNCATE);`);await db.execAsync(`VACUUM;`);}
export async function logJournalEntry(entry:Omit<JournalEntry,'id'>){const db=await getDatabase();const result=await db.runAsync(`INSERT INTO journal_entries (timestamp,type,title,content_or_uri,mood,tags) VALUES (?,?,?,?,?,?);`,[entry.timestamp,entry.type,entry.title,entry.content_or_uri,entry.mood||'',entry.tags||'']);return result.lastInsertRowId;}
export async function getAllJournalEntries(){const db=await getDatabase();return db.getAllAsync<JournalEntry>(`SELECT * FROM journal_entries ORDER BY timestamp DESC;`);} export async function deleteJournalEntry(id:number){const db=await getDatabase();await db.runAsync(`DELETE FROM journal_entries WHERE id = ?;`,[id]);}
export async function logPledge(timestamp:number){const db=await getDatabase();const result=await db.runAsync(`INSERT INTO pledges (timestamp) VALUES (?);`,[timestamp]);return result.lastInsertRowId;} export async function hasPledgedToday(){const db=await getDatabase();const startOfDay=new Date().setHours(0,0,0,0);const row=await db.getFirstAsync<{count:number}>(`SELECT COUNT(*) as count FROM pledges WHERE timestamp >= ?;`,[startOfDay]);return Boolean(row&&row.count>0);} export async function getPledgeStreak(){const db=await getDatabase();const rows=await db.getAllAsync<PledgeRecord>(`SELECT * FROM pledges ORDER BY timestamp DESC;`);return calculatePledgeStreak(rows.map(r=>r.timestamp));}
export async function logGroundingSession(responses:string[]){const db=await getDatabase();const result=await db.runAsync(`INSERT INTO grounding_sessions (timestamp,responses) VALUES (?,?);`,[Date.now(),JSON.stringify(responses)]);return result.lastInsertRowId;} export async function getGroundingSessionCount(){const db=await getDatabase();const row=await db.getFirstAsync<{count:number}>(`SELECT COUNT(*) as count FROM grounding_sessions;`);return row?row.count:0;}
export async function exportAllDataDataJSON(){const db=await getDatabase();const urges=await db.getAllAsync(`SELECT * FROM urges;`);const journals=await db.getAllAsync(`SELECT * FROM journal_entries;`);const pledges=await db.getAllAsync(`SELECT * FROM pledges;`);const groundingSessions=await db.getAllAsync(`SELECT * FROM grounding_sessions;`);return JSON.stringify({app:'Still',exportedAt:new Date().toISOString(),urges,journals,pledges,groundingSessions},null,2);}
