import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, SafeAreaView, Animated } from 'react-native';
import { Colors } from '../theme/colors';
import { authenticateWithBiometrics, verifyPinPasscode } from '../services/security';
import { ShieldCheck, Fingerprint, Lock } from 'lucide-react-native';

interface Props { biometricsEnabled: boolean; hasPinSet: boolean; onUnlocked: () => void; onUnlockedDecoy?: () => void; }
function formatLockoutMessage(ms:number){const totalSeconds=Math.ceil(ms/1000);if(totalSeconds<60)return `Too many attempts. Try again in ${totalSeconds}s.`;const minutes=Math.ceil(totalSeconds/60);return `Too many attempts. Try again in ${minutes} minute${minutes===1?'':'s'}.`;}
export const BiometricLockScreen:React.FC<Props>=({biometricsEnabled,hasPinSet,onUnlocked,onUnlockedDecoy})=>{const[pin,setPin]=useState('');const[errorMsg,setErrorMsg]=useState('');const[shakeAnim]=useState(new Animated.Value(0));const tryBiometric=async()=>{if(!biometricsEnabled)return;const success=await authenticateWithBiometrics();if(success)onUnlocked();};const triggerShake=()=>Animated.sequence([Animated.timing(shakeAnim,{toValue:10,duration:50,useNativeDriver:true}),Animated.timing(shakeAnim,{toValue:-10,duration:50,useNativeDriver:true}),Animated.timing(shakeAnim,{toValue:10,duration:50,useNativeDriver:true}),Animated.timing(shakeAnim,{toValue:0,duration:50,useNativeDriver:true})]).start();const handleKeyPress=async(num:string)=>{if(!hasPinSet||pin.length>=4)return;const newPin=pin+num;setPin(newPin);setErrorMsg('');if(newPin.length===4){const res=await verifyPinPasscode(newPin);if(res.valid){if(res.isDecoy&&onUnlockedDecoy)onUnlockedDecoy();else onUnlocked();}else{triggerShake();setErrorMsg(res.lockedOutMs?formatLockoutMessage(res.lockedOutMs):'Incorrect PIN. Try again.');setPin('');}}};const unlockHint=hasPinSet?(biometricsEnabled?'Enter your PIN or use biometrics':'Enter your 4-digit PIN'):'Use biometrics to unlock';return <SafeAreaView style={styles.container}><View style={styles.content}><View style={styles.iconBadge}><ShieldCheck size={36} color={Colors.emerald}/></View><Text style={styles.title}>Still</Text><Text style={styles.subtitle}>{unlockHint}</Text>{hasPinSet?<><Animated.View style={[styles.pinContainer,{transform:[{translateX:shakeAnim}]}]}>{[0,1,2,3].map(idx=><View key={idx} style={[styles.pinDot,pin.length>idx&&styles.pinDotFilled]}/>)}</Animated.View>{errorMsg?<Text style={styles.errorText}>{errorMsg}</Text>:null}<View style={styles.numpad}>{['1','2','3','4','5','6','7','8','9'].map(digit=><TouchableOpacity key={digit} style={styles.keyButton} onPress={()=>handleKeyPress(digit)}><Text style={styles.keyText}>{digit}</Text></TouchableOpacity>)}{biometricsEnabled?<TouchableOpacity style={styles.keyButton} onPress={tryBiometric}><Fingerprint size={24} color={Colors.emerald}/></TouchableOpacity>:<View style={styles.keySpacer}/>}<TouchableOpacity style={styles.keyButton} onPress={()=>handleKeyPress('0')}><Text style={styles.keyText}>0</Text></TouchableOpacity><TouchableOpacity style={styles.keyButton} onPress={()=>setPin(prev=>prev.slice(0,-1))}><Lock size={20} color={Colors.textSecondary}/></TouchableOpacity></View></>:null}{biometricsEnabled?<TouchableOpacity onPress={tryBiometric} style={styles.bioPromptBtn}><Text style={styles.bioPromptText}>Use Face ID / Biometrics</Text></TouchableOpacity>:null}</View></SafeAreaView>;};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:Colors.background,justifyContent:'center'},content:{paddingHorizontal:24,alignItems:'center'},iconBadge:{width:72,height:72,borderRadius:36,backgroundColor:Colors.surface,borderColor:Colors.surfaceBorder,borderWidth:1,justifyContent:'center',alignItems:'center',marginBottom:16},title:{fontSize:32,fontWeight:'700',color:Colors.textPrimary,letterSpacing:1},subtitle:{fontSize:14,color:Colors.textSecondary,marginTop:4,marginBottom:32},pinContainer:{flexDirection:'row',gap:16,marginBottom:16},pinDot:{width:16,height:16,borderRadius:8,borderWidth:2,borderColor:Colors.surfaceBorder},pinDotFilled:{backgroundColor:Colors.emerald,borderColor:Colors.emerald},errorText:{color:Colors.rose,fontSize:14,marginBottom:12},numpad:{flexDirection:'row',flexWrap:'wrap',width:280,justifyContent:'space-between',gap:16,marginTop:16},keyButton:{width:72,height:72,borderRadius:36,backgroundColor:Colors.surface,justifyContent:'center',alignItems:'center',borderColor:Colors.surfaceBorder,borderWidth:1},keySpacer:{width:72,height:72},keyText:{fontSize:24,fontWeight:'600',color:Colors.textPrimary},bioPromptBtn:{marginTop:28,paddingVertical:10,paddingHorizontal:20},bioPromptText:{color:Colors.emerald,fontSize:14,fontWeight:'600'}});
